### ISSUE TITLE
Thai Alphabet

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/morsify#1]
Thai alphabet characters are missing, someone who knows Thai can implement it.

You can add the Thai Alphabet [after the Korean one](https://github.com/ozdemirburak/morsify/blob/master/src/morsify.js#L90).

```js
'12': { // Thai Alphabet => https://th.wikipedia.org/wiki/รหัสมอร์ส
  'ก': '110'
}
```
[Wikipedia Page as the Source](https://th.wikipedia.org/wiki/%E0%B8%A3%E0%B8%AB%E0%B8%B1%E0%B8%AA%E0%B8%A1%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA)

**Comment by mahasak** [comment]
Sound interesting, I'll take this one :)

**Comment by AimeTPGM** [comment]
I'd like to contribute too! :D

**Comment by ozdemirburak** [comment]
@AimeTPGM It's okay, I can merge both pull requests if I receive pull requests from both of you.
