### ISSUE TITLE
Ukrainian leter "ґ" is missing

### ISSUE THREAD

**Issue by uaxpasha** [ozdemirburak/morsify#13]
You can see the letter Ґ here http://old.plast.org.ua/files/files/users/10701/Morse_alphabet.pdf or on Ukrainian wiki page about Morse code.
Morse Code for ґ\Ґ — "--."

**Comment by ozdemirburak** [comment]
Thanks, I've just added it.

**Comment by uaxpasha** [comment]
Thank you!
